FROM debian:bookworm-slim

# Install required packages
RUN apt-get update \
 && apt-get install -y \
            git\
            make \
            gcc \
            gcc-aarch64-linux-gnu \
            device-tree-compiler \
            nano \
            flex \
            bison \
            ncurses-base \
            swig \
            libssl-dev \
            libgnutls28-dev \
            python3-dev \
            python3-setuptools \
 && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

 # Set up the environment
RUN mkdir /workdir
WORKDIR /workdir

# Copy files
COPY files/ files/
# Copy build scripts
COPY entrypoint.sh entrypoint.sh
COPY build-arm-trusted-firmware.sh build-arm-trusted-firmware.sh
COPY build-uboot.sh build-uboot.sh

RUN chmod +x *.sh

# Set the entrypoint
#ENTRYPOINT [ "/workdir/entrypoint.sh" ]
CMD [ "/bin/bash" ]

